#!/usr/bin/env bash
# Install Nginx and the root dir to display "Hello World!"
sudo apt update
sudo apt install nginx
sudo service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
