#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
sudo apt update
sudo apt install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
new_string="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://www.youtube.com/\n\t}\n"
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
sudo sed -i "53i $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
