#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string
sudo apt update
sudo apt install nginx
sudo service nginx start
echo "Hello World!" | sudo dd status=none of=/var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
new_string="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/\n\t}\n"
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
sudo sed -i "53i $new_string" /etc/nginx/sites-available/default
new_string="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"
sudo sed -i "53i $new_string" /etc/nginx/sites-available/default
sudo service nginx reload
