#!/usr/bin/env bash
#Echo "Best School" and "Hi" using while loop and if statement
x=1
while [ $x -le 9 ]
do
	echo "Best School"
	x=$(( x + 1 ))
if [[ $x -eq 8 ]]
then
	echo "Hi"
else
	echo "Best School"
fi
