#!/usr/bin/env bash
#Code to get Apache to run on the container and to return a page containing Hello Holberton when querying the root of it
sudo apt-get -y update
sudo apt-get -y install apache2
echo 'Hello Holberton' >> /etc/apache2.conf
sudo service apache2 start
